name: Publish to pypi
'on':
  workflow_dispatch:
    inputs:
      ref:
        description: Commit/ref
        required: true
        default: main
jobs:
  build:
    name: "Build distribution \U0001F4E6"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Read .python-version
        id: python_version
        run: 'echo ::set-output name=PYTHON_VERSION::$(cat .python-version)'

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '${{ steps.python_version.outputs.PYTHON_VERSION }}'

      - name: Install and Configure uv
        uses: astral-sh/setup-uv@v5
        with:
          version: latest
          enable-cache: true

      - name: Build a binary wheel and a source tarball
        run: uv build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-testpypi:
    name: "Publish Python \U0001F40D distribution \U0001F4E6 to TestPyPI"
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: 'https://test.pypi.org/p/jsonversation'
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: "Publish distribution \U0001F4E6 to TestPyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: 'https://test.pypi.org/legacy/'
          skip-existing: true
          verbose: true
